app/chatgptclone/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
from django.urls import include, path



urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("simplechat.urls"), name="simplechat"),
    path("say_hello/", views.say_hello, name="say_hello" ),
    path("", views.say_hello, name="home" ),
]

app/simplechat/urls.py
from django.urls import path

from . import views

app_name = 'simplechat'

urlpatterns = [
    path("", views.letschat, name="chat"),
    path("get_answer", views.get_answer, name="get_answer"),
]

app/simplechat/models.py
import uuid
from django.db import models

# Roles
# Name(optional)
class Question(models.Model):
    id = models.AutoField(primary_key = True, editable = False)
    question_text = models.CharField(max_length=500)

    def __str__(self) -> str:
        return self.question_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=500)
    cost = models.DecimalField("amount charged", decimal_places=4, max_digits=8)
    tokens = models.IntegerField("tokens generated")

    def __str__(self) -> str:
        return self.answer_text

app/simplechat/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# TODO: Add the following
# 1. model = enum of models(choices)
# 2. role = enum of roles(choices)

class QnAForm(forms.Form):
    question = forms.CharField(required=True, max_length=500)

    def clean_question(self):
        # TODO: Use tiktoken to validate and generate cost
        q: str = self.cleaned_data["question"]
        if len(q) >= 500:
            raise ValidationError(_('Question is too long'))
        return q

app/chatgptclone/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.

def say_hello(request: HttpRequest) -> HttpResponse:
    return HttpResponse("Hello, world. You're using a ChatGPT Clone")

app/simplechat/views.py
from decimal import Decimal

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.http.response import HttpResponseNotAllowed

from .forms import QnAForm
from .models import Question, Answer

# Create your views here.

def _get_llm_response(question: Question) -> Answer:
    # TODO: OpenAI response
    return Answer.objects.create(
        question = question,
        answer_text = "This is a sample answer!",
        cost = Decimal(0.001),
        tokens = 100
    )

def get_answer(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        qna = QnAForm(request.POST)
        if qna.is_valid():
            question_text = qna.cleaned_data['question']
            question = Question.objects.create(question_text=question_text)
            question.save()

            answer = _get_llm_response(question)
            answer.save()
            return render(request, "index.html", context=dict(question=question_text, answer=answer))
        return render(request, "index.html", context=dict(question=request.POST.get("question", ""), answer=""))

    return HttpResponseNotAllowed(permitted_methods=['POST'])

def letschat(request: HttpRequest) -> HttpResponse:
    return render(request, "index.html", context=dict(answer=""))

app/simplechat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SastaChatGPT</title>
</head>
<body>

    {% block content %}
    {% endblock %}

</body>
</html>

app/simplechat/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="{% url 'simplechat:get_answer' %}">
        {% csrf_token %}
        <label for="question">Question:</label><br>
        <textarea id="question" name="question" rows="10" cols="30" >{{ question }}</textarea>
        <button type="submit" name="get_answer" value="get_answer">Get Answer</button>
    </form>
    <h3>Answer:</h3><br>
    <div>
        <textarea id="answer" rows="10" cols="30" readonly style="resize: both; overflow: auto;">{{ answer }}</textarea>
    </div>
{% endblock %}